[env:esp32-s3-devkitc-1-n32r16v]
platform = espressif32@6.12.0
board = esp32-s3-devkitc-1
framework = espidf
; ESP32-S3 ROM uses DOUT in the image header, then the bootloader enables OPI.
board_build.flash_mode = dout
board_upload.flash_size = 32MB
board_upload.maximum_size = 33554432
extra_scripts = pre:scripts/compiledb.py
monitor_speed = 115200
upload_protocol = esptool
test_framework = unity
test_speed = 115200
