- ros_topic_name: "/camera/head/color/image_raw"
  gz_topic_name: "/model/cleany_mecanum/head_camera/rgb/image"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "ignition.msgs.Image"
  direction: GZ_TO_ROS

- ros_topic_name: "/camera/head/depth/image_raw"
  gz_topic_name: "/model/cleany_mecanum/head_camera/depth/image"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "ignition.msgs.Image"
  direction: GZ_TO_ROS
