- ros_topic_name: "/scan"
  gz_topic_name: "/model/cleany_mecanum/lidar/scan"
  ros_type_name: "sensor_msgs/msg/LaserScan"
  gz_type_name: "gz.msgs.LaserScan"
  direction: GZ_TO_ROS

- ros_topic_name: "/scan_12cm"
  gz_topic_name: "/model/cleany_mecanum/lidar_12cm/scan"
  ros_type_name: "sensor_msgs/msg/LaserScan"
  gz_type_name: "gz.msgs.LaserScan"
  direction: GZ_TO_ROS

- ros_topic_name: "/scan_45cm"
  gz_topic_name: "/model/cleany_mecanum/lidar_45cm/scan"
  ros_type_name: "sensor_msgs/msg/LaserScan"
  gz_type_name: "gz.msgs.LaserScan"
  direction: GZ_TO_ROS

- ros_topic_name: "/scan_70cm"
  gz_topic_name: "/model/cleany_mecanum/lidar_70cm/scan"
  ros_type_name: "sensor_msgs/msg/LaserScan"
  gz_type_name: "gz.msgs.LaserScan"
  direction: GZ_TO_ROS
