[platformio]
default_envs = esp32-s3-microros-smoke
src_dir = main
include_dir = include
lib_dir = lib
data_dir = data
test_dir = test

[env:esp32-s3-microros-smoke]
platform = espressif32@6.12.0
board = esp32-s3-devkitc-1
framework = espidf
board_build.flash_mode = dout
board_upload.flash_size = 32MB
board_upload.maximum_size = 33554432
extra_scripts = pre:../scripts/microros_dependencies.py
monitor_speed = 115200
upload_protocol = esptool
