#!/usr/bin/env python3
"""Bundle the guide into index.html using only the Python standard library."""

from __future__ import annotations

import argparse
import base64
import json
from pathlib import Path
import re


ROOT = Path(__file__).resolve().parent


def build() -> str:
    manifest = json.loads((ROOT / "guide.json").read_text(encoding="utf-8"))
    payload = {
        "manifest": manifest,
        "markdown": {
            page["file"]: (ROOT / page["file"]).read_text(encoding="utf-8")
            for page in manifest["pages"]
        },
        "assets": {
            path.relative_to(ROOT).as_posix(): "data:image/svg+xml;base64,"
            + base64.b64encode(path.read_bytes()).decode("ascii")
            for path in sorted((ROOT / "assets").glob("*.svg"))
        },
        "licenses": {
            path.name: path.read_text(encoding="utf-8")
            for path in sorted((ROOT / "vendor").glob("*.LICENSE"))
        },
    }
    # A literal '<' must not terminate the HTML script element in Markdown data.
    encoded = json.dumps(payload, ensure_ascii=False, separators=(",", ":"))
    encoded = encoded.replace("<", "\\u003c").replace("\u2028", "\\u2028").replace("\u2029", "\\u2029")
    html = (ROOT / "viewer.template.html").read_text(encoding="utf-8")

    def inline_script(match: re.Match[str]) -> str:
        source = (ROOT / match[1]).read_text(encoding="utf-8")
        if re.search(r"</script", source, re.IGNORECASE):
            raise ValueError(f"Cannot safely inline script: {match[1]}")
        return f"<script>\n{source}\n</script>"

    html, count = re.subn(r'<script src="(vendor/[^"/]+\.js)"></script>', inline_script, html)
    if count != 3:
        raise ValueError(f"Expected three local browser libraries, found {count}")
    data = f"<script>window.__CLEANY_GUIDE__={encoded};</script>\n"
    html = html.replace("  <script>", data + "  <script>", 1)
    return html.replace("<!doctype html>", "<!doctype html>\n<!-- Generated by build_standalone.py; edit Markdown and viewer.template.html. -->", 1)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Fail if index.html needs regeneration")
    args = parser.parse_args()
    output = ROOT / "index.html"
    html = build()
    if args.check:
        if not output.exists() or output.read_text(encoding="utf-8") != html:
            parser.exit(1, "index.html is stale; run python3 docs/guide/build_standalone.py\n")
        print("Standalone guide is up to date")
    else:
        output.write_text(html, encoding="utf-8")
        print(f"Wrote {output} ({output.stat().st_size:,} bytes)")


if __name__ == "__main__":
    main()
