[language-server.pyright]
command = "pyright-langserver"
args = ["--stdio"]

[[language]]
name = "python"
language-servers = ["pyright"]
roots = ["pyrightconfig.json", "package.xml", "setup.py", "setup.cfg", ".git"]
